port: 7890

redir-port: 7892

mixed-port: 7893

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
# redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: true

# 仅在将allow-lan设置为true时适用
# #"*": 绑定所有IP地址
# #192.168.122.11: 绑定单个IPv4地址
# #"[aaaa::a8aa:ff:fe09:57d8]": 绑定单个IPv6地址
bind-address: "*"
ipv6: false

# 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
mode: rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / error / warning / info / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: debug

# Clash 的 RESTful API
external-controller: '127.0.0.1:9090'

hosts:
  # Firebase Cloud Messaging
  'mtalk.google.com': 108.177.125.188
  # Google Dl
  'dl.google.com': 180.163.151.161
  'dl.l.google.com': 180.163.151.161

dns:
  enable: true # 是否启用dns false
#  enhanced-mode: redir-host # 模式：redir-host或fake-ip
  listen: 0.0.0.0:7874 #
  #fake-ip-filter: # fake ip 白名单列表，如果你不知道这个参数的作用，请勿修改
     #- '*.lan'
     #- localhost.ptlogin2.qq.com
  nameserver:
    - 114.114.114.114
    - 223.6.6.6
    - 119.29.29.29
  fallback:
    - https://dns.cloudflare.com/dns-query
    - tls://dot.tiar.app
  fallback-filter:
    geoip: true
    geoip-code: CN
    domain:
      - '+.google.+'
      - '+.googleapis.com'
      - '+.googlevideo.com'
      - '+.gstatic.cn'
      - '+.gstatic.com'
      - '+.gvt1.com'
      - '+.gvt2.com'
      - '+.recaptcha.net'
      - '+.twimg.com'
      - '+.twitter.com'
      - '+.youtube.com'
      - '+.ytimg.com'
      - 'twitter.com'
      - 't.co'
      - 't.me'
      - 'telegra.ph'
      - 'youtu.be'
  # Lookup domains via specific nameservers
  nameserver-policy:
    # Alibaba
    '*.alibaba.cn': '223.6.6.6'
    '*.alibaba.com.cn': '223.6.6.6'
    '*.china.alibaba.com': '223.6.6.6'
    '*.1688.com': '223.6.6.6'
    '*.taobao.com': '223.6.6.6'
    '*.tbcache.com': '223.6.6.6'
    '*.tmall.com': '223.6.6.6'
    '*.alicdn.com': '223.6.6.6'
    '*.aliyundrive.com': '223.6.6.6'
    '*.aliyun.*': '223.6.6.6'
    '*.aliyuncdn.*': '223.6.6.6'
    '*.aliyuncs.com': '223.6.6.6'
    '*.aliyundunwaf.com': '223.6.6.6'
    '*.aliapp.com': '223.6.6.6'
    '*.aliapp.org': '223.6.6.6'
    '*.alibabausercontent.com': '223.6.6.6'
    '*.mmstat.com': '223.6.6.6'
    'tb.cn': '223.6.6.6'

# Clash for Windows
# Proxies module latency test settings
cfw-latency-timeout: 3000
cfw-latency-url: http://www.gstatic.com/generate_204


#自定义配置目录
#cfw-profiles-path: 'C:\Users\Administrator\.config\clash\profiles'

# 打断连接
# Identify strategy of breaking connections after switching to a new proxy/profile/mode
# Options for proxy: none, chain(proxy group in connection chains), all
# Options for profile: true, false
# Options for mode: true, false
cfw-conn-break-strategy:
  proxy: chain # none/chain/all
  profile: true # true/false
  mode: true # true/false

cfw-proxies-order: default



proxies:

# 服务器节点订阅
proxy-providers:

  HK:
    type: http
    path: ./Provider/Proxy/Sub/HK.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    filter: '港|HK|Hong Kong|Macau'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  TW:
    type: http
    path: ./Provider/Proxy/Sub/TW.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    filter: '台|新北|彰化|TW|Taiwan'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  US:
    type: http
    path: ./Provider/Proxy/Sub/US.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    filter: '美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  JP:
    type: http
    path: ./Provider/Proxy/Sub/JP.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    filter: '日本|JP|Japan'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  KR:
    type: http
    path: ./Provider/Proxy/Sub/SG.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    filter: 'KR|Korea|KOR|首尔|韩|韓'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
      
   
  SA:
    type: http
    path: ./Provider/Proxy/Sub/SA.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    filter: 'Mexico|Argentina|Chile|Costa Rica|阿根廷|巴西|智利|Philippines|India|Turkey|Egypt|菲律宾|印度|土耳其|德国|埃及|Germany|Bulgaria|Spain|Netherlands|United Kingdom|保加利亚|西班牙|荷兰|英国a'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  TR:
    type: http
    path: ./Provider/Proxy/Sub/TR.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    filter: '土耳其|TR|Turkey'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  
  UN:
    type: http
    path: ./Provider/Proxy/Sub/UN.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

proxy-groups:
  - name: "🚀 Proxy"
    type: select
    proxies:
      - ✈️ Server
      - 🇨🇳 TW
      - 🇺🇲 US
      - 🇭🇰 HK
      - 🇯🇵 JP
      - 🇸🇬 SG
      - 🇰🇷 KR
      
  - name: "✈️ Server"
    type: select
    use:
      - UN
      
  - name: "📹 Youtube"
    type: select
    proxies:
      - 🇺🇲 US
      - 🚀 Proxy
      - 🇸🇬 SG
      - 🇨🇳 TW
      
  - name: "🎥 Netflix"
    type: select
    proxies:
      - 🇨🇳 TW
      - 🇸🇬 SG
      - 🇯🇵 JP
      - 🇭🇰 HK
      - 🇺🇲 US
      - 🇰🇷 KR
      - ✈️ Server
      
  - name: "📲 Telegram"
    type: select
    proxies:
      - 🇭🇰 HK
      - 🇨🇳 TW
      - 🇯🇵 JP
      
  - name: "📺 PrimeVideo"
    type: select
    proxies:
      - 🇨🇳 TW
      - 🇺🇲 US
      - ❄️ Rare
      
  - name: "🏀 StarPlus"
    type: select
    use:
      - SA
      
  - name: "🇨🇳 TW"
    type: select
    use:
      - TW
      
  - name: "🇺🇲 US"
    type: select
    use:
      - US
      
  - name: "🇭🇰 HK"
    type: select
    use:
      - HK
      
  - name: "🇯🇵 JP"
    type: select
    use:
      - JP

  - name: "🇸🇬 SG"
    type: select
    use:
      - SG
      
  - name: "🇰🇷 KR"
    type: select
    use:
      - KR
      
  - name: "❄️ Rare"
    type: select
    use:
      - SA
      
  - name: "📢 FCM"
    type: select
    proxies:
      - 🇭🇰 HK
      - 🇨🇳 TW
      - DIRECT
      
  - name: "🌍 GlobalMedia"
    type: select
    proxies:
      - 🇭🇰 HK
      - 🇨🇳 TW
      - 🇸🇬 SG
      - 🇯🇵 JP
      - 🇺🇲 US
      - 🇰🇷 KR
      - ✈️ Server
      
  - name: "📺 BiliBili"
    type: select
    proxies:
      - 🎯 Direct
      - 🇨🇳 TW
      - 🇭🇰 HK

  - name: "🐟 Other"
    type: select
    proxies:
      - 🚀 Proxy
      - DIRECT
      - 🇭🇰 HK
      - 🇨🇳 TW
      - 🇺🇲 US
      - 🇸🇬 SG
      - 🇰🇷 KR
      
  - name: "Ⓜ️ Microsoft"
    type: select
    proxies:
      - DIRECT
      - 🚀 Proxy
      - 🇺🇲 US
      - 🇭🇰 HK
      
  - name: "🍎 Apple"
    type: select
    proxies:
      - DIRECT
      - 🚀 Proxy
      - 🇺🇲 US
      - 🇭🇰 HK
      - 🇨🇳 TW
      - 🇯🇵 JP
      
  - name: "🎮 Game"
    type: select
    proxies:
      - DIRECT
      - 🚀 Proxy
      - 🇺🇲 US
      - 🇭🇰 HK
      
  - name: "🎯 Direct"
    type: select
    proxies:
      - DIRECT
      - 🚀 Proxy
      
  - name: "🛑 Reject"
    type: select
    proxies:
      - REJECT
      - DIRECT

# 关于 Rule Provider 请查阅：https://lancellc.gitbook.io/clash/clash-config-file/rule-provider

rule-providers:
# name: # Provider 名称
#   type: http # http 或 file
#   behavior: classical # 或 ipcidr、  - DOMAIN
#   path: # 文件路径
#   url: # 只有当类型为 HTTP 时才可用，您不需要在本地空间中创建新文件。
#   interval: # 自动更新间隔，仅在类型为 HTTP 时可用

  LocalAreaNetwork:
    type: http
    behavior: classical
    path: ./Provider/LocalAreaNetwork.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml
    interval: 86400

  UnBan:
    type: http
    behavior: classical
    path: ./Provider/UnBan.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml
    interval: 86400
    
  Pikpak:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Pikpak.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/Pikpak.yaml
    interval: 86400
    

  EmbyDirect:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/EmbyDirect.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/EmbyDirect.yaml
    interval: 86400
    
  BanAD:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Guard/BanAD.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml
    interval: 86400

  BanProgramAD:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Guard/BanProgramAD.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml
    interval: 86400

  PrimeVideo:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/PrimeVideo.yaml
    url: https://raw.githubusercontent.com/HotKids/Rules/master/Clash/RuleSet/Prime%20Video.yaml
    interval: 86400

  GoogleFCM:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/GoogleFCM.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml
    interval: 86400

  GoogleCN:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/GoogleCN.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleCN.yaml
    interval: 86400

  SteamCN:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/SteamCN.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/SteamCN.yaml
    interval: 86400

  OneDrive:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/OneDrive.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OneDrive.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Microsoft.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    path: ./Provider/Ruleset/Apple.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Apple.yaml
    interval: 86400
    
  Telegram:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Telegram.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Telegram.yaml
    interval: 86400

  Epic:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Epic.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Epic.yaml
    interval: 86400

  Sony:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Sony.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Sony.yaml
    interval: 86400

  Steam:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Steam.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Steam.yaml
    interval: 86400

  Youtube:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Youtube.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Youtube.yaml
    interval: 86400
    
  Emby:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Emby.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/ACL4SSR/master/Clash/Providers/Ruleset/Emby.yaml
    interval: 86400
    
  StreamingTW:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/StreamingTW.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/Streaming_TW.yaml
    interval: 86400

  HBOGO:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/HBOGO.yaml
    url: https://raw.githubusercontent.com/HotKids/Rules/master/Clash/RuleSet/HBO_Go.yaml
    interval: 86400

  Line:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Line.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Line/Line.yaml
    interval: 86400

  Facebook:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Facebook.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.yaml
    interval: 86400

  StreamingJP:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/StreamingJP.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/Streaming_JP.yaml
    interval: 86400
    
  StreamingUS:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/StreamingUS.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/Streaming_US.yaml
    interval: 86400
    
    
#  LeaguePass:
#    type: http
#    behavior: classical
#    path: ./Provider/RuleSet/LeaguePass.yaml
#    url: https://raw.githubusercontent.com/JamesLiu0802/ACL4SSR/master/Clash/Providers/Ruleset/NBA.yaml
#    interval: 86400   
    
  StarPlus:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/StarPlus.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/StarPlus.yaml
    interval: 86400

  Porn:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Porn.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/Porn.yaml
    interval: 86400

  Pornhub:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Pornhub.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/Pornhub.yaml
    interval: 86400

  DisneyPlus:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/DisneyPlus.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/DisneyPlus.yaml
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Netflix.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Netflix.yaml
    interval: 86400
 
  BilibiliHMT:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/BilibiliHMT.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/BilibiliHMT.yaml
    interval: 86400
    
  Bilibili:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Bilibili.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bilibili.yaml
    interval: 86400
    
  ChinaMedia:
    type: http
    behavior: classical
    path: ./Provider/ChinaMedia.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaMedia.yaml
    interval: 86400
    
  ProxyMedia:
    type: http
    behavior: classical
    path: ./Provider/ProxyMedia.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml
    interval: 86400
    
  HK:
    type: http
    behavior: classical
    path: ./Provider/Ruleset/HK.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/HK.yaml
    interval: 86400

  Whatsapp:
    type: http
    behavior: classical
    path: ./Provider/Ruleset/Whatsapp.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Whatsapp/Whatsapp.yaml
    interval: 86400
    
  TW:
    type: http
    behavior: classical
    path: ./Provider/Ruleset/TW.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/TW.yaml
    interval: 86400
    
  US:
    type: http
    behavior: classical
    path: ./Provider/Ruleset/US.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/US.yaml
    interval: 86400
    
  ProxyGFWlist:
    type: http
    behavior: classical
    path: ./Provider/ProxyGFWlist.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyGFWlist.yaml
    interval: 86400
    
  ChinaDOMAIN:
    type: http
    behavior: classical
    path: ./Provider/ChinaDOMAIN.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDOMAIN.yaml
    interval: 86400
    
  ChinaCompanyIp:
    type: http
    behavior: ipcidr
    path: ./Provider/ChinaCompanyIp.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaCompanyIp.yaml
    interval: 86400
    
  Download:
    type: http
    behavior: classical
    path: ./Provider/Download.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Download.yaml
    interval: 86400
    

# 规则
rules:
  # Unbreak
  - RULE-SET,LocalAreaNetwork,🎯 Direct
  - RULE-SET,UnBan,🎯 Direct
  - RULE-SET,Pikpak,🚀 Proxy
  - RULE-SET,EmbyDirect,🎯 Direct

  # AdBlock
  - RULE-SET,BanAD,🛑 Reject
  - RULE-SET,BanProgramAD,🛑 Reject
  
  # FCM
  - RULE-SET,GoogleFCM,📢 FCM
  - RULE-SET,GoogleCN,🎯 Direct

  - RULE-SET,SteamCN,🎯 Direct
  
  #Microsoft & Apple
  - RULE-SET,OneDrive,Ⓜ️ Microsoft
  - RULE-SET,Microsoft,Ⓜ️ Microsoft
  - RULE-SET,Apple,🍎 Apple
  
  # Telegram
  - RULE-SET,Telegram,📲 Telegram

  # Game
  - RULE-SET,Epic,🎮 Game
  - RULE-SET,Sony,🎮 Game
  - RULE-SET,Steam,🎮 Game

  # Streaming
  - RULE-SET,Youtube,📹 Youtube
  - RULE-SET,Emby,🇺🇲 US
#  - RULE-SET,LeaguePass,LeaguePass
  - RULE-SET,PrimeVideo,📺 PrimeVideo
  - RULE-SET,StreamingTW,🇨🇳 TW
  - RULE-SET,HBOGO,🇨🇳 TW
  - RULE-SET,Line,🇨🇳 TW
  - RULE-SET,Facebook,🇨🇳 TW
  - RULE-SET,StreamingJP,🇯🇵 JP
  - RULE-SET,StreamingUS,🇺🇲 US
  - RULE-SET,StarPlus,🏀 StarPlus
  - RULE-SET,Porn,🇺🇲 US
  - RULE-SET,Pornhub,🇺🇲 US
  - RULE-SET,DisneyPlus,🎥 Netflix
  - RULE-SET,Netflix,🎥 Netflix
  - RULE-SET,BilibiliHMT,📺 BiliBili
  - RULE-SET,Bilibili,📺 BiliBili
  
  - RULE-SET,ChinaMedia,🎯 Direct
  - RULE-SET,ProxyMedia,🌍 GlobalMedia
  - RULE-SET,US,🇺🇲 US
  - RULE-SET,TW,🇨🇳 TW
  - RULE-SET,Whatsapp,🇭🇰 HK
  - RULE-SET,ProxyGFWlist,🚀 Proxy
  - RULE-SET,HK,🇭🇰 HK
  - RULE-SET,ChinaDOMAIN,🎯 Direct
  - RULE-SET,ChinaCompanyIp,🎯 Direct
  - RULE-SET,Download,🎯 Direct
  - GEOIP,CN,🎯 Direct

  - MATCH,🐟 Other
